enable-ssh-support

pinentry-program /run/current-system/sw/bin/pinentry-env
# pinentry-program /run/current-system/sw/bin/pinentry-mac
# pinentry-program /run/current-system/sw/bin/pinentry-tty

# dont ask for PIN if run < 10min
default-cache-ttl-ssh 600
default-cache-ttl     600

# but not longer than 2h
max-cache-ttl-ssh     7200
max-cache-ttl         7200
