#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                               \
    active_window_opacity        1.0          \
    auto_balance                 off          \
    bottom_padding               0            \
    focus_follows_mouse          off          \
    insert_feedback_color        0xffd75f5f   \
    layout                       stack        \
    left_padding                 0            \
    mouse_action1                move         \
    mouse_action2                resize       \
    mouse_drop_action            swap         \
    mouse_follows_focus          off          \
    mouse_modifier               fn           \
    normal_window_opacity        0.90         \
    right_padding                0            \
    split_ratio                  0.50         \
    split_type                   auto         \
    top_padding                  0            \
    window_gap                   0            \
    window_opacity               off          \
    window_opacity_duration      0.0          \
    window_origin_display        default      \
    window_placement             second_child \
    window_shadow                on           \
    window_zoom_persist          on

# yabai -m query --displays | jq .
# macbook-air
#yabai -m config --display 37D8832A-2D66-02CA-B9F7-8F30A301B230 \
#    left_padding    0 \
#    right_padding   0
# external
#yabai -m config --display 37D8832A-2D66-02CA-B9F7-8F30A301B230 \
#    laoyout bsp \
#    left_padding    452 \
#    right_padding   452
#yabai -m space --balance

# Spaces
yabai -m space 1 --label "terminal"
yabai -m space 2 --label "editor"
yabai -m space 3 --label "web"
yabai -m space 4 --label "comm"
yabai -m space 5 --label "misc"

# Attach to spaces
yabai -m rule --add app="(Firefox|Brave Browser)" space="^web"
yabai -m rule --add app="(Google Meet|Mail|Discord|Status|Element|Telegram|Rocket.Chat)" space="^comm"
yabai -m rule --add app!="(Alacritty|Firefox|Brave Browser|Google Meet|Mail|Discord|Status|Element|Telegram|Rocket.Chat)" space="^misc"
yabai -m rule --add app="(Reeder)" space="^misc"

# Floating
yabai -m rule --add title="^Page Info .*$" manage=off
yabai -m rule --add title="Info$" manage=off
yabai -m rule --add title="UTM" manage=off
# Notes
yabai -m rule --add app="Alacritty" title="Notes" manage=off

echo "yabai configuration loaded.."
