#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0             \
    bottom_padding               0             \
    left_padding                 0             \
    right_padding                0             \
    window_gap                   0             \
    layout                       stack            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# 3440 - 2560 = 880
#yabai -m config layout bsp
#yabai -m space 1 --padding abs:0:0:452:452
#yabai -m space 2 --padding abs:0:0:452:452
#yabai -m space 3 --padding abs:0:0:452:452
#yabai -m space 4 --padding abs:0:0:452:452
#yabai -m space 5 --padding abs:0:0:452:452
#yabai -m space 6 --padding abs:0:0:452:452
#yabai -m space 7 --padding abs:0:0:452:452
#yabai -m space 8 --padding abs:0:0:452:452
#yabai -m space 9 --padding abs:0:0:452:452
#yabai -m space 0 --padding abs:0:0:452:452
yabai -m space --balance

# Spaces
yabai -m space 1 --label "terminal"
yabai -m space 2 --label "editor"
yabai -m space 3 --label "web"
yabai -m space 4 --label "comm"
yabai -m space 5 --label "misc"

# Attach to spaces
yabai -m rule --add app="(Firefox|Brave Browser)" space="^web"
yabai -m rule --add app="(Google Meet|Mail|Discord|Status|Element|Telegram|Rocket.Chat)" space="^comm"
yabai -m rule --add app!="(Alacritty|Firefox|Brave Browser|Google Meet|Mail|Discord|Status|Element|Telegram|Rocket.Chat)" space="^misc"
yabai -m rule --add app="(Reeder)" space="^misc"

# Floating
yabai -m rule --add title="^Page Info .*$" manage=off
yabai -m rule --add title="Info$" manage=off
yabai -m rule --add title="UTM" manage=off
# Notes
yabai -m rule --add app="Alacritty" title="Notes" manage=off

echo "yabai configuration loaded.."
